[tool.pygbag]
# Nombre mostrado en la app web
app_name = "Trilero"
# Script principal
entrypoint = "main.py"
# Incluir carpeta de assets completa en el paquete web
assets = [
  "assets/**/*"
]
# No empaquetar en .pyz (mejor para depurar en web)
archive = false
# Tiempo m√°ximo de precarga de assets (segundos)
preload = 30
